stages:
  - build
  - unit test
  - integration test
  - functional test
  - push github

build engine:
  stage: build
  script:
    - docker build -t continous_learning/engine:nightly -f docker/engine.Dockerfile source

test engine:
  stage: unit test
  before_script:
    - docker run --rm -d --name redis -p 6379:6379 redis:latest
  script:
    - docker run --rm continous_learning/engine:nightly python engine/servicer_test.py
  after_script:
    - docker kill redis
