stages:
  - clean up
  - build
  - unit test
  - functional test
  - deploy

clean up:
  stage: clean up
  before_script:
    - docker build -t continous_learning/docker-compose:nightly -f docker/docker-compose.Dockerfile source
  script:
    - docker run -rm -v /var/run/docker.sock:/var/run/docker.sock continous_learning/docker-compose:nightly stop
    - docker run -rm -v /var/run/docker.sock:/var/run/docker.sock continous_learning/docker-compose:nightly rm -f

build web:
  stage: build
  script:
    - docker build -t continous_learning/web:nightly -f docker/web.Dockerfile source

deploy:
  stage: deploy
  script:
    - docker run -rm -v /var/run/docker.sock:/var/run/docker.sock continous_learning/docker-compose:nightly create
    - docker run -rm -v /var/run/docker.sock:/var/run/docker.sock continous_learning/docker-compose:nightly start
