stages:
  - build
  - unit test
  - integration test
  - functional test
  - push github

build engine:
  stage: build
  script:
    - docker build -t continous_learning/engine:nightly -f docker/engine.Dockerfile source
