stages:
  - build
  - unit test
  - integration test
  - functional test
  - push github

build engine:
  stage: build
  script:
    - docker build -t continous_learning/engine:nightly -f docker/engine.Dockerfile source

test engine:
  stage: unit test
  script:
    - docker run --rm continous_learning/engine:nightly python engine/servicer_test.py
